### ISSUE TITLE
Refactor away Chai

### ISSUE THREAD

**Issue by onlurking** [garageScript/curriculum#343]
Several tests across `generalAlgorithms`, `interviewPrep`, `js7` and `j8` are using chai:

```javascript
const expect = require('chai').expect
```

but the dependency is not declared in `package.json`.

**Comment by songz** [comment]
TODO: Migrate tests to all use jest.

**Comment by onlurking** [comment]
@songz can you assign me? working on it.

**Comment by onlurking** [comment]
@songz @ggwadera done, just opened PR #360
