### ISSUE TITLE
JS3 Problem 4: Duplicate values in test case

### ISSUE THREAD

**Issue by Oroul** [garageScript/curriculum#347]
The description for this problem is:

> Write a function that takes in an array of numbers and a number, and returns true if any pairs add up to the number. (The numbers in the array is unique, meaning there will be no duplicate numbers) solution([1,2,22,333,23], 25) // returns true solution([1,2,22,333,23], 24) // returns true

However, the last test case tests the input `[0, 0, 0], 0`, all duplicate values.

Is the test case wrong, or is the description wrong for this problem?

**Comment by songz** [comment]
description is wrong.

**Comment by SlyBouhafs** [comment]
Looks like this issue has already been solved by someone else. 

Here's a screenshot as a reference: 

![Screen Shot 2020-09-13 at 23 35 28](https://user-images.githubusercontent.com/1410462/93030322-06176300-f61a-11ea-94d1-76be68e894d6.png)

**Comment by SlyBouhafs** [comment]
I did a pull request here #355 so that the description in js3/4.js matches the one on the website.
